output_dir: ~/scratch/protein_output

dataset:
  class: MyFold
  path: {{ datadir }}
  transform:
    class: Compose
    transforms:
      - class: ProteinView
        view: residue
      - class: TruncateProtein
        max_length: 550

task:
  class: FoldClassification
  model:
    class: ESM
    path: {{ modeldir }}
    model: {{ model }}
  mlp_batch_norm: True
  mlp_dropout: 0.2

optimizer:
  class: Adam
  lr: 1.0e-4

scheduler:
  class: ReduceLROnPlateau
  factor: 0.6
  patience: 5

engine:
  gpus: [0] #, 1, 2, 3]
  batch_size: 8
  log_interval: 1000

lr_ratio: 0.1

eval_metric: accuracy

train:
  num_epoch: 50